### ISSUE TITLE
Error: IndexError: list index out of range

### ISSUE THREAD

**Issue by mindwellsolutions** [sheikhartin/google-scholar-scraper#3]
Thanks in advance, this is such a helpful app, would love to have this one bug fixed. 

Sometimes when I search it gives me this error. Even when I run the most basic search:  python core.py "Covid"
All dependencies were installed successfully with: pip install -r requirements.txt .  Running Ubuntu 22.04.2 Locally.

If you could also advise the best way to search for 2 keywords at once: Would it be "keyword1" "keyword 2" or "keyword1 keyword2" or otherwise in the prompt. Thanks.

**Bash Prompt Used When Error Appears:** python3 core.py "cbd covid" -s 2022 -e 2023

Fetching request #18 from https://scholar.google.com/scholar?start=170&q=cbd+covid&hl=en&lr=lang_en&as_sdt=0,5&as_ylo=2020&as_yhi=2023
Traceback (most recent call last):
  File "/home/agentgpt/google-scholar-scraper/core.py", line 234, in <module>
    results = pd.DataFrame(gs_spider.fetch())
  File "/home/agentgpt/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 711, in __init__
    data = list(data)
  File "/home/agentgpt/google-scholar-scraper/core.py", line 62, in fetch
    for item in self.parse(response):
  File "/home/agentgpt/google-scholar-scraper/core.py", line 98, in parse
    year = re.search(r'\d{4,}$', snippet[-2]) or re.search(r'\d{4,}$', snippet[-1])
IndexError: list index out of range

**Comment by sheikhartin** [comment]
Hey @mindwellsolutions, thank you for your kind comment!

Are you using the default version of Ubuntu 22.04, i.e. 3.10? And which version of this scraper do you have?
```bash
$ python -V # Default version of Python
$ python3 -V
$ git tag | tail -1 # To see the last tag
```

I ran `python core.py "Covid"` and tried about 10 related search pages offline and no such problem; this is a bit strange, this error should occur if the displayed item does not have enough metadata/snippet! Such an error happened to me in the past and I don't hide the problem, but it only happened to old things! — The link you gave is for another prompt (pay attention to the years)

Also, you can use several keywords inside a quote and the program supports it (the rest is related to Google Scholar's back-end)...

**Comment by sheikhartin** [comment]
You can help me more by saving a page [as HTML] and scrape it offline! If it's not difficult for you, use the following script:
```python
import re

from requests_html import HTML

FILEPATH = '<path_to_the_html_file>'
with open(FILEPATH) as f:
    doc = f.read()

html = HTML(html=doc)
articles = html.xpath('//div[@class="gs_r gs_or gs_scl"]')

for article in articles:
    title = article.xpath('//h3[@class="gs_rt"]/a | .//h3[@class="gs_rt"]/span[2]', first=True).text
    print(f'Title: {title}')
    snippet = article.xpath('//div[@class="gs_a"]', first=True).text
    snippet = [elem.strip() for elem in snippet.replace('\xa0', '').split('- ')]
    print(f'Snippet: {snippet}')
    authors = snippet[0]
    print(f'Authors: {authors}')
    year = re.search(r'\d{4,}$', snippet[-2]) or re.search(r'\d{4,}$', snippet[-1])
    year = year.group() if year is not None else None
    print(f'Year: {year}')
    source = article.xpath('//h3[@class="gs_rt"]/a/@href', first=True)
    print(f'Source: {source}')
    paper = article.xpath('//div[@class="gs_or_ggsm"]/a/@href', first=True)
    print(f'Paper: {paper}')
    citations_no = article.xpath('//div[@class="gs_ri"]/div[@class="gs_fl"]/a[3][contains(., "Cited by")]', first=True)
    citations_no = citations_no.text.replace('Cited by ', '') if citations_no is not None else None
    print(f'Citation #: {citations_no}')
    print('=====')
```

If you encounter an error, please let me know.

**Comment by mindwellsolutions** [comment]
> Hey @mindwellsolutions, thank you for your kind comment!
> 
> Are you using the default version of Ubuntu 22.04, i.e. 3.10? And which version of this scraper do you have?
> 
> ```shell
> $ python -V # Default version of Python
> $ python3 -V
> $ git tag | tail -1 # To see the last tag
> ```
> 
> I ran `python core.py "Covid"` and tried about 10 related search pages offline and no such problem; this is a bit strange, this error should occur if the displayed item does not have enough metadata/snippet! Such an error happened to me in the past and I don't hide the problem, but it only happened to old things! — The link you gave is for another prompt (pay attention to the years)
> 
> Also, you can use several keywords inside a quote and the program supports it (the rest is related to Google Scholar's back-end)...

Hi, thank you so much for the help, it's truly greatly appreciated. This script is phenomenal when it works for me, such a helpful tool, so thankful for all the work you've spent on it. 

I'm using the default Ubuntu 22.04.2 Jammy Jellyfish with Python 3.10.6 and Git Tag | tail -1 = Version 1.4.0 (Newest Build), I used Git Clone and then pip install -r requirements.txt before running.

I'll try out the recommendation you gave to test out a local scraping of an HTML file. Although, it seems that it reads multiple pages before giving the error.

**Here is the full error I'm getting:**
![image](https://github.com/sheikhartin/google-scholar-scraper/assets/38707551/e98c3c77-ba60-4333-8582-dc4923e94577)

**Comment by mindwellsolutions** [comment]
The test code you sent worked. Which I kind of expected to work, because the regular script successfully fetches information from 8+ pages before crashing with error.  

I think I might have figured out when this error happens. If I set the date range between 2 different years "-s 2022 -e 2023" then I get the error, but if I do the same search with the same year "-s 2023 -e 2023" It completes successfully. 

I also appear to get this error when I have 2 words in the search query, even if I search the same year (See Screenshot 3). This actually mirrors my original error, because I searched "cbd covid" as a 2 keyword query search and also selected a date range of more than 1 year:

**(Error) Different Year Date Search (1 keyword) : (-s 2022 -e 2023) python core.py "cbd" -s 2022 -e 2023**
![image](https://github.com/sheikhartin/google-scholar-scraper/assets/38707551/34077993-b115-47a6-86cd-5d9be5f3c175)

**(Successful : No Error) Same Year Date Search (1 keyword) : (-s 2023 -e 2023) python core.py "cbd" -s 2023 -e 2023**
![image](https://github.com/sheikhartin/google-scholar-scraper/assets/38707551/afc853b4-98c3-4d79-bb5f-e7d8d6574198)

**(Error) (2 Keywords): Same Year Date Search: (-s 2023 -e 2023) python core.py "cbd covid" -s 2023 -e 2023**
![image](https://github.com/sheikhartin/google-scholar-scraper/assets/38707551/65226585-7c4a-4e7a-99ee-7d1b209cf8e3)

**Test Code Results From the Py Script you sent (Screenshot): Completed Successfully**
![image](https://github.com/sheikhartin/google-scholar-scraper/assets/38707551/ad816ed2-4c10-4e19-b678-0f48624e73e8)

**pip install -r requirements.txt (Successful Screenshot):**
![image](https://github.com/sheikhartin/google-scholar-scraper/assets/38707551/0cdc9c51-2f01-4452-8714-17ea466298b7)

**Comment by sheikhartin** [comment]
Oh, go to [this](https://scholar.google.com/scholar?start=70&q=cbd+covid&hl=en&lr=lang_en&as_sdt=0,5&as_ylo=2022&as_yhi=2023) page and look at "The Use of Social Media Applications on Business Performance in the Covid 19 Era: A Study of Selected MSMES in Nairobi Central Business District"! After about a year, I have not come across a case that has only one value in its metadata...

Anyway, I solved the problem and now you can clone/pull version `1.4.1` and use it! :)

**Comment by mindwellsolutions** [comment]
> Anyway, I solved the problem and now you can clone/pull version `1.4.1` and use it! :)

Thank you so much for working to resolve this on the fly. Sorry for the couple questions in a row. I deleted the old folder and downloaded the new 1.4.1 build but got this error:

**Command: python core.py "cbd covid" -s 2023 -e 2023**

**Error:**
python core.py "cbd covid" -s 2023 -e 2023
  File "/home/agentgpt/google-scholar-scraper-1.4.1/core.py", line 99
    year = re.search(r'\d{4,}$', snippet[-2]) or re.search(r'\d{4,}$', snippet[-1])
TabError: inconsistent use of tabs and spaces in indentation

![image](https://github.com/sheikhartin/google-scholar-scraper/assets/38707551/873e0c4a-b8ea-42da-9349-4171fb8f687a)

**Comment by sheikhartin** [comment]
These questions make me think more about my old code... I apologize again, it probably works now! (In version `1.4.2`)

**Comment by mindwellsolutions** [comment]
Thank you so much for helping resolve this, it's beyond appreciated. All of the searches I've tried now are working 100% <3.  Really appreciate this app.

Two quick questions: 

1) Is there a way to search for quoted grouped words, so it only detects them when they are side by side. 
Example: python core.py "cb1 receptor" "multiple sclerosis" -s 2023 -e 2023
      -   Where cb1 & receptor have to be together and multiple & sclerosis have to be together to match.
      
2) Is there a way to limit results to only Study Titles that have the keywords in the title. It appears to pick up any study that has those terms anywhere in the body of text within the study.

Thank again for such a helpful script :)

**Comment by sheikhartin** [comment]
For your first question, the following link may be useful (the program supports only one prompt): 
https://pitt.libguides.com/googlescholar/searchtips

And for the second one, I must say that this scraper was created from the beginning for this purpose, but due to the lack of Google Scholar support in this field, we used the method of sorting based on citations — there is no way for it yet!

Few users care about the status of the program and if it doesn't work for them, they go to the next one; but you chose here and I appreciate your choice... :relaxed:

**Comment by mindwellsolutions** [comment]
Thank you again for the support to resolve these small issues on the fly. :) App works perfectly now.
